version: '3'

volumes:
  static:

services:
  redis:
    image: redis
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./config/nginx/prod:/etc/nginx/conf.d
      - static:/static
    depends_on:
      - web
  web:
    image: scprdev/docker-chartwerk
    env_file:
      - ./config/env/prod.env
    command: ["./scripts/bootstrap.sh"]
    volumes:
      - .:/code
      - static:/static
    expose:
      - "8000"
    links:
      - redis
    depends_on:
      - redis